version: "3.3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=my_bdd
      - POSTGRES_USER=antonio
      - POSTGRES_PASSWORD=Kjzd1827
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pcsdp@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
    - 5050:80
